//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NursingHomeApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientLogin
    {
        public int Id { get; set; }
        public string PersonId { get; set; }
        public byte[] Password { get; set; }
        public int PatientId { get; set; }
    
        public virtual Patient Patient { get; set; }
    }
}
