//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NursingHomeApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientMedicine
    {
        public int Id { get; set; }
        public Nullable<int> Dose { get; set; }
        public Nullable<System.TimeSpan> Term { get; set; }
        public int MedicineId { get; set; }
        public int PatientId { get; set; }
    
        public virtual Medicine Medicine { get; set; }
        public virtual PatientForm Patient { get; set; }
    }
}
